version: '3'
services:
  minecraft-server:
    container_name: minecraft_server
    build:
      context: /home/minecraft_user/server/minecraft_docker
    ports:
      - "25565:25565"
    environment:
      - EULA=true
      - MINECRAFT_VERSION=1.20
    volumes:
      - minecraftdata:/minecraft/world
    restart: on-failure

volumes:
  minecraftdata:
    external: true
